/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookRequest } from '../../models/book-request';

export interface SaveBook$Params {
  body: BookRequest
}

export function saveBook(http: HttpClient, rootUrl: string, params: SaveBook$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
  const rb = new RequestBuilder(rootUrl, saveBook.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context }) // <-- changed from 'blob' to 'text'
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      const bookId = parseFloat(r.body); // parse the text response to number
      if (isNaN(bookId)) {
        throw new Error(`Invalid book ID returned from server: ${r.body}`);
      }
      return r.clone({ body: bookId }) as StrictHttpResponse<number>;
    })
  );
}

saveBook.PATH = '/books';
