spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/book_social_network
    username: username
    password: user123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: manav
    password: manav
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: d4f3a79e6c2b1f8a9de34b5c6a7f90b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e60
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
server:
  port: 8088
